### ISSUE TITLE
Cleaner-7.4.2 vs. ODFE1.2

### ISSUE THREAD

**Issue by dbt4u** [TrumanDu/cleaner#4]
Hello Dear Cleaners,

1000thx for your 7.4.2 Version. It is just a Manifest-Flag to make it runnable also on an ODFE 1.2 aka Kibana 7.2.0? Or is there more magic inside? Or it is becaus ODFE 1.x is based on the Elastic-OSS Branch? Did you have testet a Cleaner 7x Version with a ODFE 1.x Version?

Here the error message:
Plugin installation was unsuccessful due to error "Plugin cleaner [7.4.2] is incompatible with Kibana [7.2.0].

Can you build a 7.2 / ODFE 1.2 compatible Version? Or can you shou how we can tweak it without re-building?

**Comment by TrumanDu** [comment]
@CodeFreezr u can use 
[cleaner-7.2.0.zip](https://github.com/TrumanDu/cleaner/files/3889841/cleaner-7.2.0.zip).
If available, please feedback to me. thanks.

**Comment by tmidi** [comment]
@TrumanDu, I was able to install Cleaner. After the install I was not able to get the list of indices and Kibana would "crash" with the following error:
`{"type":"error","@timestamp":"2019-12-02T17:01:40Z","tags":[],"pid":1,"level":"error","error":{"message":"[index_not_found_exception] no such index [.cleaner], with { resource.type="index_or_alias" & resource.id=".cleaner" & index_uuid="_na_" & index=".cleaner" }","name":"Error","stack":"[index_not_found_exception] no such index [.cleaner], with { resource.type="index_or_alias" & resource.id=".cleaner" & index_uuid="_na_" & index=".cleaner" } :: {"path":"/.cleaner/_count","query":{},"statusCode":404,"response":"{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.cleaner]","resource.type":"index_or_alias","resource.id":".cleaner","index_uuid":"_na_","index":".cleaner"}],"type":"index_not_found_exception","reason":"no such index [.cleaner]","resource.type":"index_or_alias","resource.id":".cleaner","index_uuid":"_na_","index":".cleaner"},"status":404}"}
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:315:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:274:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/cleaner/list","path":"/api/cleaner/list","href":"/api/cleaner/list"},"message":"[index_not_found_exception] no such index [.cleaner], with { resource.type="index_or_alias" & resource.id=".cleaner" & index_uuid="_na_" & index=".cleaner" }"}`

I was able to resolve this by create `.cleaner` index:
`
PUT .cleaner
`

**Comment by TrumanDu** [comment]
@tmidi yeah,thanks. the reason is create `.cleaner` index error.i will check it.

**Comment by dbt4u** [comment]
We could succesfully install cleaner-7.2.0.zip into ODFE-1.2.0 Kibana. But cleaner didn't clean.

We have received for e.g. this log:
`{"type":"error","@timestamp":"2019-12-10T08:18:06Z","tags":["warning","process"],"pid":1,"level":"error","error":{"message":"TypeError: Cannot read property 'getCluster' of undefined\n    at Object.getCluster [as run] (/usr/share/kibana/plugins/cleaner/server/scheduleJob.js:146:48)\n    at Plugin.run [as externalInit] (/usr/share/kibana/plugins/cleaner/index.js:64:22)\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\n    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7407:25)\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)\n    at callHookOnPlugins (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:49:37)\n    at KbnServer.initializeMixin (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:54:9)","name":"UnhandledPromiseRejectionWarning","stack":"UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCluster' of undefined\n    at Object.getCluster [as run] (/usr/share/kibana/plugins/cleaner/server/scheduleJob.js:146:48)\n    at Plugin.run [as externalInit] (/usr/share/kibana/plugins/cleaner/index.js:64:22)\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\n    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7407:25)\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)\n    at callHookOnPlugins (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:49:37)\n    at KbnServer.initializeMixin (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:54:9)\n    at emitWarning (internal/process/promises.js:81:15)\n    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)\n    at process._tickCallback (internal/process/next_tick.js:69:34)"},"message":"TypeError: Cannot read property 'getCluster' of undefined\n    at Object.getCluster [as run] (/usr/share/kibana/plugins/cleaner/server/scheduleJob.js:146:48)\n    at Plugin.run [as externalInit] (/usr/share/kibana/plugins/cleaner/index.js:64:22)\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\n    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7407:25)\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)\n    at callHookOnPlugins (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:49:37)\n    at KbnServer.initializeMixin (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:54:9)"}`

Any Idea what went wrong?

**Comment by TrumanDu** [comment]
@CodeFreezr i will check it.

**Comment by dbt4u** [comment]
Did you need further Informations to find the bug? If yes, what kind of Infos we can provide?

**Comment by TrumanDu** [comment]
@CodeFreezr sorry,be busy recently.i will fix it quickly.

**Comment by dbt4u** [comment]
carefull, pleasant ping...
meanwhile we have also a odfe 1.3 aka Elastic OSS 1.3. Elastic 1.5 seems also very smart...
