### ISSUE TITLE
Cleaner in Elastic 7.4.2 OSS vs. Basic

### ISSUE THREAD

**Issue by dbt4u** [TrumanDu/cleaner#6]
We have found out the cleaner 7.4 did work with the Elastic 7.4.2 Stack Basic Version, but not with the 7.4.2 OSS Version. Perhaps in the OSS Version is no Elastic Index Management included? Just a guess.

Here an error we found inside 7.4.2 OSS Version, we did not found inside a 7.4.2 Basic Version:

`{"log":"{\"type\":\"error\",\"@timestamp\":\"2020-01-29T08:38:33Z\",\"tags\":[\"warning\",\"process\"],\"pid\":6,\"level\":\"error\",\"error\":{\"message\":\"TypeError
: Cannot read property 'getCluster' of undefined\\n    at Object.getCluster [as run] (/usr/share/kibana/plugins/cleaner/server/scheduleJob.js:146:48)\\n    at Plugin.r
un [as externalInit] (/usr/share/kibana/plugins/cleaner/index.js:64:22)\\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\\n
  at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.
js:100:28)\\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7411:25)\\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_
plugin_hook.js:53:25)\\n    at callHookOnPlugins (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:49:37)\\n    at KbnServer.initializeMixin (/usr/share
/kibana/src/legacy/server/plugins/initialize_mixin.js:54:9)\",\"name\":\"UnhandledPromiseRejectionWarning\",\"stack\":\"UnhandledPromiseRejectionWarning: TypeError: Ca
nnot read property 'getCluster' of undefined\\n    at Object.getCluster [as run] (/usr/share/kibana/plugins/cleaner/server/scheduleJob.js:146:48)\\n    at Plugin.run [
as externalInit] (/usr/share/kibana/plugins/cleaner/index.js:64:22)\\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\\n    at
 internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:1
00:28)\\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7411:25)\\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plug
in_hook.js:53:25)\\n    at callHookOnPlugins (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:49:37)\\n    at KbnServer.initializeMixin (/usr/share/kib
ana/src/legacy/server/plugins/initialize_mixin.js:54:9)\\n    at emitWarning (internal/process/promises.js:81:15)\\n    at emitPromiseRejectionWarnings (internal/proce
ss/promises.js:120:9)\\n    at process._tickCallback (internal/process/next_tick.js:69:34)\"},\"message\":\"TypeError: Cannot read property 'getCluster' of undefined\\
n    at Object.getCluster [as run] (/usr/share/kibana/plugins/cleaner/server/scheduleJob.js:146:48)\\n    at Plugin.run [as externalInit] (/usr/share/kibana/plugins/cl
eaner/index.js:64:22)\\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\\n    at internals.Server.register (/usr/share/kibana/
node_modules/hapi/lib/server.js:431:35)\\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\\n    at Plugin.init (/usr/share/kibana
/node_modules/lodash/index.js:7411:25)\\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)\\n    at callHookOnPlugins (
/usr/share/kibana/src/legacy/server/plugins/initialize_mixin.js:49:37)\\n    at KbnServer.initializeMixin (/usr/share/kibana/src/legacy/server/plugins/initialize_mixin
.js:54:9)\"}\n","stream":"stdout","time":"2020-01-29T08:38:33.197047501Z"}
`

**Comment by TrumanDu** [comment]
@CodeFreezr sorry,because of 2019-nCoV,I don't have much energy to deal with this problem.When the epidemic is over, I will fix it as soon as possible

**Comment by 8wlgns** [comment]
@CodeFreezr 
I think add it " require: ['elasticsearch'], " 
above https://github.com/TrumanDu/cleaner/blob/master/index.js#L27 line
will be solve this problem!
